@startuml schoolclass_student
class Student {
.. Private Properties ..
- Number #id
- String #firstName
- String #lastName
- String #birthDate
- {static} Number #idCounter
.. Getter ..
+ get id()
+ get firstName()
+ get lastName()
+ get birthDate()
+ {static} get idCounter()
+ constructor(firstName, lastName, birthDate)
+ getInfo()
}
class SchoolClass {
.. Private Properties ..
- String #className
- Map #students
- Number #maxStudents
.. Getter ..
+ get students()
+ get className()
+ get maxStudents()
+ constructor(className, maxStudents)
.. Methods ..
+ addStudent(student)
+ getStudent(id)
+ removeStudent(id)
+ findStudent(firstname, lastname)
+ getStudentTable()
+ clear()
}
SchoolClass *-- Student
@enduml